name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Download Tailscale
      run: |
        url="https://pkgs.tailscale.com/stable/Tailscale.pkg"
        output="Tailscale.pkg"
        echo "Downloading Tailscale from $url..."
        curl -fsSL "$url" -o "$output"
        if [ ! -f "$output" ]; then
          echo "Failed to download Tailscale installer."
          exit 1
        fi
        echo "Downloaded Tailscale installer successfully."
        ls -la

    - name: Install Tailscale
      run: |
        installer -pkg Tailscale.pkg -target /

    - name: Auth Tailscale
      run: |
        auth_key="${TAILSCALE_AUTH_KEY}"
        echo "Authenticating Tailscale with key: $auth_key..."
        sudo tailscale up --authkey="$auth_key"
        if [ $? -ne 0 ]; then
          echo "Tailscale authentication failed."
          exit 1
        fi
      env:
        TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}

    - name: Enable Remote Desktop
      run: |
        echo "Enabling Remote Desktop..."
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -users runneradmin -privs -all -restart -agent -menu -on
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -allowAccessFor -allUsers -privs -all -restart -agent -menu -on
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -firewall -on
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -firewall -add -ports -TCP 5900
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -access -on -users runneradmin -privs -all -restart -agent -menu -on

    - name: Set Local User Password
      run: |
        echo "Setting password for runneradmin..."
        sudo dscl . -passwd /Users/runneradmin P@ssw0rd!

    - name: Verify Tailscale Installation
      run: |
        echo "Verifying Tailscale installation..."
        tailscale status
        if [ $? -ne 0 ]; then
          echo "Tailscale is not installed correctly."
          exit 1
        fi
        echo "Tailscale is installed successfully."

    - name: Check Tailscale Logs
      run: |
        echo "Checking Tailscale logs..."
        sudo cat /var/log/tailscaled.log
