name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download Tailscale
      run: |
        $url = "https://pkgs.tailscale.com/stable/tailscale-setup-full-1.80.2.exe"
        $output = "tailscale-setup-full-1.80.2.exe"
        Write-Host "Downloading Tailscale from $url..."
        Invoke-WebRequest -Uri $url -OutFile $output
        if (-Not (Test-Path $output)) {
          throw "Failed to download Tailscale installer."
        }
    - name: Install Tailscale
      run: |
        $installerPath = "tailscale-setup-full-1.80.2.exe"
        if (-Not (Test-Path $installerPath)) {
          throw "Tailscale installer not found."
        }
        Write-Host "Running Tailscale installation..."
        $logFilePath = "D:\a\_temp\tailscale-install.log"
        New-Item -ItemType Directory -Force -Path "D:\a\_temp"
        Start-Process -FilePath $installerPath -ArgumentList "/S /L=$logFilePath" -Wait
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Tailscale installation failed. Checking log file for details..."
          if (Test-Path $logFilePath) {
            Get-Content $logFilePath
          } else {
            Write-Host "Log file not found at $logFilePath"
          }
          throw "Tailscale installation failed."
        }
    - name: Auth Tailscale
      run: |
        $authKey = $Env:TAILSCALE_AUTH_KEY
        Write-Host "Authenticating Tailscale with key: $authKey..."
        tailscale up --authkey=$authKey
        if ($LASTEXITCODE -ne 0) {
          throw "Tailscale authentication failed."
        }
      env:
        TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Set Local User Password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Start Tailscale Service
      run: |
        Write-Host "Starting Tailscale service..."
        Start-Service Tailscale
        if ($LASTEXITCODE -ne 0) {
          throw "Failed to start Tailscale service."
        }
