name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download Tailscale
      run: |
        $url = "https://pkgs.tailscale.com/stable/${{ secrets.TAILSCALE_AUTH_KEY }}?format=msi"
        Invoke-WebRequest $url -OutFile tailscale.msi
      env:
        TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
    - name: Install Tailscale
      run: msiexec /i tailscale.msi /quiet
    - name: Auth Tailscale
      run: tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }}
    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Set Local User Password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Start Tailscale Service
      run: Start-Service Tailscale
