name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download Tailscale
      run: |
        $url = "https://pkgs.tailscale.com/stable/${{ secrets.TAILSCALE_AUTH_KEY }}?format=msi"
        Invoke-WebRequest $url -OutFile tailscale.msi
      env:
        TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
    - name: Install Tailscale
      run: msiexec /i tailscale.msi /quiet
    - name: Auth Tailscale
      run: tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }}
